package telas;

import modelo.Fcp;
import jpa.FcpJPA;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadastroFcp extends javax.swing.JFrame {

    public CadastroFcp() {
        initComponents();
    }

    private DefaultTableModel montarTabela(List<Fcp> listaFcp) {
        String[] colunas = {"ID", "Aliquota", "Base Legal", "Valido até"};
        DefaultTableModel tabela = new DefaultTableModel();
        tabela.setColumnIdentifiers(colunas);

        for (int i = 0; listaFcp.size() > i; i++) {
            Fcp fcp = listaFcp.get(i);

            String[] linha = {
                Integer.toString(fcp.getId()),
                fcp.getAliquota(),
                fcp.getBaseLegal(),
                fcp.getValidoAte()
            };
            tabela.addRow(linha);
        }
        return tabela;
    }

    private String getIdItemSelecionado() {
        int posicao = jtableFcp.getSelectedRow();
        if (posicao == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela!");
        }
        return (String) jtableFcp.getValueAt(posicao, 0);
    }

    private Fcp fcpEdicao = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtBaseLegal = new javax.swing.JTextField();
        txtAliquota = new javax.swing.JTextField();
        txtValidoAte = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableFcp = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuCadastro = new javax.swing.JMenu();
        jmenuAliquotaFCP = new javax.swing.JMenuItem();
        jmenuAliquotaICMS = new javax.swing.JMenuItem();
        jmenuAliquotaPISCOFINS = new javax.swing.JMenuItem();
        jmenuCategoria = new javax.swing.JMenuItem();
        jmenuCEST = new javax.swing.JMenuItem();
        jmenuCST = new javax.swing.JMenuItem();
        jmenuNCM = new javax.swing.JMenuItem();
        jmenuOrigem = new javax.swing.JMenuItem();
        jmenuProduto = new javax.swing.JMenuItem();
        jmenuRelatorio = new javax.swing.JMenu();
        jmenuProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE ALIQUOTA DE FCP");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Aliquota");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Base Legal");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("Valido até");

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtBaseLegal.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtBaseLegal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAliquota.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtAliquota.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtValidoAte.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtValidoAte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtValidoAte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidoAteActionPerformed(evt);
            }
        });

        jtableFcp.setModel(montarTabela(FcpJPA.listar()));
        jtableFcp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtableFcpFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jtableFcp);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValidoAte)
                                    .addComponent(txtBaseLegal)
                                    .addComponent(txtAliquota, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btnSalvar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluir)))))))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAliquota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBaseLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValidoAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jmenuCadastro.setText("Cadastro");
        jmenuCadastro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jmenuAliquotaFCP.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuAliquotaFCP.setText("Aliquota FCP");
        jmenuAliquotaFCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuAliquotaFCPActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuAliquotaFCP);

        jmenuAliquotaICMS.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuAliquotaICMS.setText("Aliquota ICMS");
        jmenuAliquotaICMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuAliquotaICMSActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuAliquotaICMS);

        jmenuAliquotaPISCOFINS.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuAliquotaPISCOFINS.setText("Aliquota PIS e COFINS");
        jmenuAliquotaPISCOFINS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuAliquotaPISCOFINSActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuAliquotaPISCOFINS);

        jmenuCategoria.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuCategoria.setText("Categoria");
        jmenuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCategoriaActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuCategoria);

        jmenuCEST.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuCEST.setText("CEST");
        jmenuCEST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCESTActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuCEST);

        jmenuCST.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuCST.setText("CST");
        jmenuCST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCSTActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuCST);

        jmenuNCM.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuNCM.setText("NCM");
        jmenuNCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuNCMActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuNCM);

        jmenuOrigem.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuOrigem.setText("Origem");
        jmenuOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuOrigemActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuOrigem);

        jmenuProduto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuProduto.setText("Produto");
        jmenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuProdutoActionPerformed(evt);
            }
        });
        jmenuCadastro.add(jmenuProduto);

        jMenuBar1.add(jmenuCadastro);

        jmenuRelatorio.setText("Relatório");
        jmenuRelatorio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jmenuProdutos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jmenuProdutos.setText("Produtos");
        jmenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuProdutosActionPerformed(evt);
            }
        });
        jmenuRelatorio.add(jmenuProdutos);

        jMenuBar1.add(jmenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuAliquotaFCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuAliquotaFCPActionPerformed
        CadastroFcp cadFCP = new CadastroFcp();
        cadFCP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuAliquotaFCPActionPerformed

    private void jmenuAliquotaICMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuAliquotaICMSActionPerformed
        CadastroIcms cadICMS = new CadastroIcms();
        cadICMS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuAliquotaICMSActionPerformed

    private void jmenuAliquotaPISCOFINSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuAliquotaPISCOFINSActionPerformed
        CadastroPis cadPis = new CadastroPis();
        cadPis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuAliquotaPISCOFINSActionPerformed

    private void jmenuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCategoriaActionPerformed
        CadastroCategoria cadCat = new CadastroCategoria();
        cadCat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuCategoriaActionPerformed

    private void jmenuCESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCESTActionPerformed
        CadastroCest cadCest = new CadastroCest();
        cadCest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuCESTActionPerformed

    private void jmenuCSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCSTActionPerformed
        CadastroCst cadCst = new CadastroCst();
        cadCst.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuCSTActionPerformed

    private void jmenuNCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuNCMActionPerformed
        CadastroNcm cadNcm = new CadastroNcm();
        cadNcm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuNCMActionPerformed

    private void jmenuOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuOrigemActionPerformed
        CadastroOrigem cadOrig = new CadastroOrigem();
        cadOrig.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuOrigemActionPerformed

    private void jmenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuProdutoActionPerformed
        CadastroProduto cadProd = new CadastroProduto();
        cadProd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuProdutoActionPerformed

    private void jmenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuProdutosActionPerformed
        RelatorioProdutos rtProd = new RelatorioProdutos();
        rtProd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenuProdutosActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Fcp fcp = new Fcp();
        fcp.setAliquota(txtAliquota.getText());
        fcp.setBaseLegal(txtBaseLegal.getText());
        fcp.setValidoAte(txtValidoAte.getText());

        if (fcpEdicao != null) {
            fcpEdicao.setAliquota(txtAliquota.getText());
            fcpEdicao.setBaseLegal(txtBaseLegal.getText());
            fcpEdicao.setValidoAte(txtValidoAte.getText());
            FcpJPA.atualizar(fcpEdicao);
            JOptionPane.showMessageDialog(null, "FCP atualizada com sucesso!");

        } else {
            FcpJPA.cadastrar(fcp);
            JOptionPane.showMessageDialog(null, "FCP cadastrada com sucesso!");

        }
        jtableFcp.setModel(montarTabela(FcpJPA.listar()));
        jScrollPane1.setViewportView(jtableFcp);

        txtAliquota.setText("");
        txtBaseLegal.setText("");
        txtValidoAte.setText("");

        fcpEdicao = null;
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        FcpJPA.excluir(Integer.parseInt(getIdItemSelecionado()));
        jtableFcp.setModel(montarTabela(FcpJPA.listar()));
        jScrollPane1.setViewportView(jtableFcp);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtValidoAteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidoAteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidoAteActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idSelecionado = getIdItemSelecionado();
        fcpEdicao = FcpJPA.obter(Integer.parseInt(idSelecionado));
        txtAliquota.setText(fcpEdicao.getAliquota());
        txtBaseLegal.setText(fcpEdicao.getBaseLegal());
        txtValidoAte.setText(fcpEdicao.getValidoAte());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jtableFcpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtableFcpFocusGained

    }//GEN-LAST:event_jtableFcpFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fcp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fcp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fcp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fcp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFcp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmenuAliquotaFCP;
    private javax.swing.JMenuItem jmenuAliquotaICMS;
    private javax.swing.JMenuItem jmenuAliquotaPISCOFINS;
    private javax.swing.JMenuItem jmenuCEST;
    private javax.swing.JMenuItem jmenuCST;
    private javax.swing.JMenu jmenuCadastro;
    private javax.swing.JMenuItem jmenuCategoria;
    private javax.swing.JMenuItem jmenuNCM;
    private javax.swing.JMenuItem jmenuOrigem;
    private javax.swing.JMenuItem jmenuProduto;
    private javax.swing.JMenuItem jmenuProdutos;
    private javax.swing.JMenu jmenuRelatorio;
    private javax.swing.JTable jtableFcp;
    private javax.swing.JTextField txtAliquota;
    private javax.swing.JTextField txtBaseLegal;
    private javax.swing.JTextField txtValidoAte;
    // End of variables declaration//GEN-END:variables
}
